/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

/**
 *
 * @author bucci.alex
 */
public class FRMGara extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRMGara.class.getName());

    /**
     * Creates new form FRMGara
     */
    public FRMGara() {
        initComponents();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblStato1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblStato2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblStato3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblStato4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbVelocita = new javax.swing.JComboBox<>();
        btnAvvia = new javax.swing.JButton();
        btnSospendi = new javax.swing.JButton();
        btnRiprendi = new javax.swing.JButton();
        btnFerma = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pbCorridore1 = new javax.swing.JProgressBar();
        pbCorridore2 = new javax.swing.JProgressBar();
        pbCorridore3 = new javax.swing.JProgressBar();
        pbCorridore4 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relay Runners");
        setMinimumSize(new java.awt.Dimension(705, 421));
        setPreferredSize(new java.awt.Dimension(705, 421));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(4, 2, 0, 5));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Runner 1");
        jPanel5.add(jLabel1);

        lblStato1.setForeground(new java.awt.Color(0, 0, 0));
        lblStato1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStato1.setText("0");
        jPanel5.add(lblStato1);

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Runner 2");
        jPanel6.add(jLabel3);

        lblStato2.setForeground(new java.awt.Color(0, 0, 0));
        lblStato2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStato2.setText("0");
        jPanel6.add(lblStato2);

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Runner 3");
        jPanel7.add(jLabel5);

        lblStato3.setForeground(new java.awt.Color(0, 0, 0));
        lblStato3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStato3.setText("0");
        jPanel7.add(lblStato3);

        jPanel2.add(jPanel7);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Runner 4");
        jPanel4.add(jLabel7);

        lblStato4.setForeground(new java.awt.Color(0, 0, 0));
        lblStato4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStato4.setText("0");
        jPanel4.add(lblStato4);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        cmbVelocita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Slow", "Regular", "Fast" }));
        cmbVelocita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(cmbVelocita, new java.awt.GridBagConstraints());

        btnAvvia.setText("Avvia");
        btnAvvia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvvia, new java.awt.GridBagConstraints());

        btnSospendi.setText("Sospendi");
        btnSospendi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSospendi.setEnabled(false);
        jPanel1.add(btnSospendi, new java.awt.GridBagConstraints());

        btnRiprendi.setText("Riprendi");
        btnRiprendi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRiprendi.setEnabled(false);
        jPanel1.add(btnRiprendi, new java.awt.GridBagConstraints());

        btnFerma.setText("Ferma");
        btnFerma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFerma.setEnabled(false);
        jPanel1.add(btnFerma, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(4, 1, 10, 5));

        pbCorridore1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pbCorridore1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(pbCorridore1);

        pbCorridore2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel3.add(pbCorridore2);

        pbCorridore3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel3.add(pbCorridore3);

        pbCorridore4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel3.add(pbCorridore4);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        btnSospendi.setEnabled(true);
        btnFerma.setEnabled(true);

        Corridore c;
        Thread t;

        t = new Thread(c = new Corridore());
        t.start();
        
        

    }//GEN-LAST:event_btnAvviaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnFerma;
    private javax.swing.JButton btnRiprendi;
    private javax.swing.JButton btnSospendi;
    private javax.swing.JComboBox<String> cmbVelocita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblStato1;
    private javax.swing.JLabel lblStato2;
    private javax.swing.JLabel lblStato3;
    private javax.swing.JLabel lblStato4;
    private javax.swing.JProgressBar pbCorridore1;
    private javax.swing.JProgressBar pbCorridore2;
    private javax.swing.JProgressBar pbCorridore3;
    private javax.swing.JProgressBar pbCorridore4;
    // End of variables declaration//GEN-END:variables
}
